### PR TITLE
Custom tags are ignored in app LeafRenderer

### PR DESCRIPTION
**Pull request by Igor-Palaguta**
Custom tags were ignored, just default tags are used

### CODE REVIEW

**Comment by 0xTim** [comment]
@Igor-Palaguta could you write a test to ensure the custom tags get passed through?

**Comment by Igor-Palaguta** [comment]
@0xTim thanks for reply. Yes sure, but after tau version is released is this bug still exist?

**Comment by 0xTim** [comment]
See the release notes for final prerelease here https://github.com/vapor/leaf/releases/tag/4.0.0-zeta.1

Tau is being split into a separate renderer so I'm guessing this is still applicable in Leaf

**Comment by Igor-Palaguta** [comment]
will add tests

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
